"""add heropoers association table

Revision ID: 1efab2552799
Revises: c704e91d742c
Create Date: 2024-10-10 11:50:34.233117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efab2552799'
down_revision = 'c704e91d742c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('power_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_hero_powers_power_id', 'powers', ['power_id'], ['id'])
        batch_op.create_foreign_key('fk_hero_powers_hero_id', 'heroes', ['hero_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hero_powers_power_id', type_='foreignkey')
        batch_op.drop_constraint('fk_hero_powers_hero_id', type_='foreignkey')
        batch_op.drop_column('power_id')
        batch_op.drop_column('hero_id')

    # ### end Alembic commands ###
