"""add Power

Revision ID: 34069228f798
Revises: d6bb6e6bdcfc
Create Date: 2024-10-09 16:41:48.322534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34069228f798'
down_revision = 'd6bb6e6bdcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('powers')
    # ### end Alembic commands ###
